# Generated by Django 3.1.4 on 2021-01-08 21:04

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('flow', models.FloatField(default=0)),
                ('quality', models.IntegerField(choices=[(1, 'Good'), (2, 'Estimated'), (3, 'Suspect'), (4, 'Unchecked'), (5, 'Missing')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
